// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: resourceplatform_admin.proto

package controlplanegrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdminCatalogService_ListK8SClusters_FullMethodName                      = "/resourceplatform.admin.AdminCatalogService/ListK8sClusters"
	AdminCatalogService_GetK8SCluster_FullMethodName                        = "/resourceplatform.admin.AdminCatalogService/GetK8sCluster"
	AdminCatalogService_CreateK8SCluster_FullMethodName                     = "/resourceplatform.admin.AdminCatalogService/CreateK8sCluster"
	AdminCatalogService_UpdateK8SCluster_FullMethodName                     = "/resourceplatform.admin.AdminCatalogService/UpdateK8sCluster"
	AdminCatalogService_DeleteK8SCluster_FullMethodName                     = "/resourceplatform.admin.AdminCatalogService/DeleteK8sCluster"
	AdminCatalogService_RevalidateK8SCluster_FullMethodName                 = "/resourceplatform.admin.AdminCatalogService/RevalidateK8sCluster"
	AdminCatalogService_ListResourceDefinitions_FullMethodName              = "/resourceplatform.admin.AdminCatalogService/ListResourceDefinitions"
	AdminCatalogService_CreateResourceDefinition_FullMethodName             = "/resourceplatform.admin.AdminCatalogService/CreateResourceDefinition"
	AdminCatalogService_ListResourceDefinitionZoneSupport_FullMethodName    = "/resourceplatform.admin.AdminCatalogService/ListResourceDefinitionZoneSupport"
	AdminCatalogService_ReplaceResourceDefinitionZoneSupport_FullMethodName = "/resourceplatform.admin.AdminCatalogService/ReplaceResourceDefinitionZoneSupport"
	AdminCatalogService_UpdateResourceDefinitionStatus_FullMethodName       = "/resourceplatform.admin.AdminCatalogService/UpdateResourceDefinitionStatus"
	AdminCatalogService_DeleteResourceDefinition_FullMethodName             = "/resourceplatform.admin.AdminCatalogService/DeleteResourceDefinition"
	AdminCatalogService_ListResourceTemplateCatalog_FullMethodName          = "/resourceplatform.admin.AdminCatalogService/ListResourceTemplateCatalog"
	AdminCatalogService_ListResourceTemplates_FullMethodName                = "/resourceplatform.admin.AdminCatalogService/ListResourceTemplates"
	AdminCatalogService_GetResourceTemplate_FullMethodName                  = "/resourceplatform.admin.AdminCatalogService/GetResourceTemplate"
	AdminCatalogService_CreateResourceTemplate_FullMethodName               = "/resourceplatform.admin.AdminCatalogService/CreateResourceTemplate"
	AdminCatalogService_UpdateResourceTemplate_FullMethodName               = "/resourceplatform.admin.AdminCatalogService/UpdateResourceTemplate"
	AdminCatalogService_DeleteResourceTemplate_FullMethodName               = "/resourceplatform.admin.AdminCatalogService/DeleteResourceTemplate"
	AdminCatalogService_GetClusterNodesAdmin_FullMethodName                 = "/resourceplatform.admin.AdminCatalogService/GetClusterNodesAdmin"
)

// AdminCatalogServiceClient is the client API for AdminCatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminCatalogServiceClient interface {
	ListK8SClusters(ctx context.Context, in *ListK8SClustersRequest, opts ...grpc.CallOption) (*ListK8SClustersResponse, error)
	GetK8SCluster(ctx context.Context, in *GetK8SClusterRequest, opts ...grpc.CallOption) (*AdminK8SClusterDetail, error)
	CreateK8SCluster(ctx context.Context, in *CreateK8SClusterRequest, opts ...grpc.CallOption) (*AdminK8SClusterDetail, error)
	UpdateK8SCluster(ctx context.Context, in *UpdateK8SClusterRequest, opts ...grpc.CallOption) (*AdminK8SClusterDetail, error)
	DeleteK8SCluster(ctx context.Context, in *DeleteK8SClusterRequest, opts ...grpc.CallOption) (*DeleteK8SClusterResponse, error)
	RevalidateK8SCluster(ctx context.Context, in *RevalidateK8SClusterRequest, opts ...grpc.CallOption) (*AdminK8SClusterDetail, error)
	ListResourceDefinitions(ctx context.Context, in *ListResourceDefinitionsRequest, opts ...grpc.CallOption) (*ListResourceDefinitionsResponse, error)
	CreateResourceDefinition(ctx context.Context, in *CreateResourceDefinitionRequest, opts ...grpc.CallOption) (*CreateResourceDefinitionResponse, error)
	ListResourceDefinitionZoneSupport(ctx context.Context, in *ListResourceDefinitionZoneSupportRequest, opts ...grpc.CallOption) (*ListResourceDefinitionZoneSupportResponse, error)
	ReplaceResourceDefinitionZoneSupport(ctx context.Context, in *ReplaceResourceDefinitionZoneSupportRequest, opts ...grpc.CallOption) (*ReplaceResourceDefinitionZoneSupportResponse, error)
	UpdateResourceDefinitionStatus(ctx context.Context, in *UpdateResourceDefinitionStatusRequest, opts ...grpc.CallOption) (*AdminResourceDefinition, error)
	DeleteResourceDefinition(ctx context.Context, in *DeleteResourceDefinitionRequest, opts ...grpc.CallOption) (*DeleteResourceDefinitionResponse, error)
	ListResourceTemplateCatalog(ctx context.Context, in *ListResourceTemplateCatalogRequest, opts ...grpc.CallOption) (*ListResourceTemplateCatalogResponse, error)
	ListResourceTemplates(ctx context.Context, in *ListResourceTemplatesRequest, opts ...grpc.CallOption) (*ListResourceTemplatesResponse, error)
	GetResourceTemplate(ctx context.Context, in *GetResourceTemplateRequest, opts ...grpc.CallOption) (*AdminResourceTemplate, error)
	CreateResourceTemplate(ctx context.Context, in *CreateResourceTemplateRequest, opts ...grpc.CallOption) (*AdminResourceTemplate, error)
	UpdateResourceTemplate(ctx context.Context, in *UpdateResourceTemplateRequest, opts ...grpc.CallOption) (*AdminResourceTemplate, error)
	DeleteResourceTemplate(ctx context.Context, in *DeleteResourceTemplateRequest, opts ...grpc.CallOption) (*DeleteResourceTemplateResponse, error)
	GetClusterNodesAdmin(ctx context.Context, in *GetClusterNodesAdminRequest, opts ...grpc.CallOption) (*GetClusterNodesAdminResponse, error)
}

type adminCatalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminCatalogServiceClient(cc grpc.ClientConnInterface) AdminCatalogServiceClient {
	return &adminCatalogServiceClient{cc}
}

func (c *adminCatalogServiceClient) ListK8SClusters(ctx context.Context, in *ListK8SClustersRequest, opts ...grpc.CallOption) (*ListK8SClustersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListK8SClustersResponse)
	err := c.cc.Invoke(ctx, AdminCatalogService_ListK8SClusters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) GetK8SCluster(ctx context.Context, in *GetK8SClusterRequest, opts ...grpc.CallOption) (*AdminK8SClusterDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminK8SClusterDetail)
	err := c.cc.Invoke(ctx, AdminCatalogService_GetK8SCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) CreateK8SCluster(ctx context.Context, in *CreateK8SClusterRequest, opts ...grpc.CallOption) (*AdminK8SClusterDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminK8SClusterDetail)
	err := c.cc.Invoke(ctx, AdminCatalogService_CreateK8SCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) UpdateK8SCluster(ctx context.Context, in *UpdateK8SClusterRequest, opts ...grpc.CallOption) (*AdminK8SClusterDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminK8SClusterDetail)
	err := c.cc.Invoke(ctx, AdminCatalogService_UpdateK8SCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) DeleteK8SCluster(ctx context.Context, in *DeleteK8SClusterRequest, opts ...grpc.CallOption) (*DeleteK8SClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteK8SClusterResponse)
	err := c.cc.Invoke(ctx, AdminCatalogService_DeleteK8SCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) RevalidateK8SCluster(ctx context.Context, in *RevalidateK8SClusterRequest, opts ...grpc.CallOption) (*AdminK8SClusterDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminK8SClusterDetail)
	err := c.cc.Invoke(ctx, AdminCatalogService_RevalidateK8SCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) ListResourceDefinitions(ctx context.Context, in *ListResourceDefinitionsRequest, opts ...grpc.CallOption) (*ListResourceDefinitionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourceDefinitionsResponse)
	err := c.cc.Invoke(ctx, AdminCatalogService_ListResourceDefinitions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) CreateResourceDefinition(ctx context.Context, in *CreateResourceDefinitionRequest, opts ...grpc.CallOption) (*CreateResourceDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateResourceDefinitionResponse)
	err := c.cc.Invoke(ctx, AdminCatalogService_CreateResourceDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) ListResourceDefinitionZoneSupport(ctx context.Context, in *ListResourceDefinitionZoneSupportRequest, opts ...grpc.CallOption) (*ListResourceDefinitionZoneSupportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourceDefinitionZoneSupportResponse)
	err := c.cc.Invoke(ctx, AdminCatalogService_ListResourceDefinitionZoneSupport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) ReplaceResourceDefinitionZoneSupport(ctx context.Context, in *ReplaceResourceDefinitionZoneSupportRequest, opts ...grpc.CallOption) (*ReplaceResourceDefinitionZoneSupportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplaceResourceDefinitionZoneSupportResponse)
	err := c.cc.Invoke(ctx, AdminCatalogService_ReplaceResourceDefinitionZoneSupport_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) UpdateResourceDefinitionStatus(ctx context.Context, in *UpdateResourceDefinitionStatusRequest, opts ...grpc.CallOption) (*AdminResourceDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResourceDefinition)
	err := c.cc.Invoke(ctx, AdminCatalogService_UpdateResourceDefinitionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) DeleteResourceDefinition(ctx context.Context, in *DeleteResourceDefinitionRequest, opts ...grpc.CallOption) (*DeleteResourceDefinitionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResourceDefinitionResponse)
	err := c.cc.Invoke(ctx, AdminCatalogService_DeleteResourceDefinition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) ListResourceTemplateCatalog(ctx context.Context, in *ListResourceTemplateCatalogRequest, opts ...grpc.CallOption) (*ListResourceTemplateCatalogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourceTemplateCatalogResponse)
	err := c.cc.Invoke(ctx, AdminCatalogService_ListResourceTemplateCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) ListResourceTemplates(ctx context.Context, in *ListResourceTemplatesRequest, opts ...grpc.CallOption) (*ListResourceTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourceTemplatesResponse)
	err := c.cc.Invoke(ctx, AdminCatalogService_ListResourceTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) GetResourceTemplate(ctx context.Context, in *GetResourceTemplateRequest, opts ...grpc.CallOption) (*AdminResourceTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResourceTemplate)
	err := c.cc.Invoke(ctx, AdminCatalogService_GetResourceTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) CreateResourceTemplate(ctx context.Context, in *CreateResourceTemplateRequest, opts ...grpc.CallOption) (*AdminResourceTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResourceTemplate)
	err := c.cc.Invoke(ctx, AdminCatalogService_CreateResourceTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) UpdateResourceTemplate(ctx context.Context, in *UpdateResourceTemplateRequest, opts ...grpc.CallOption) (*AdminResourceTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminResourceTemplate)
	err := c.cc.Invoke(ctx, AdminCatalogService_UpdateResourceTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) DeleteResourceTemplate(ctx context.Context, in *DeleteResourceTemplateRequest, opts ...grpc.CallOption) (*DeleteResourceTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResourceTemplateResponse)
	err := c.cc.Invoke(ctx, AdminCatalogService_DeleteResourceTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminCatalogServiceClient) GetClusterNodesAdmin(ctx context.Context, in *GetClusterNodesAdminRequest, opts ...grpc.CallOption) (*GetClusterNodesAdminResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterNodesAdminResponse)
	err := c.cc.Invoke(ctx, AdminCatalogService_GetClusterNodesAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminCatalogServiceServer is the server API for AdminCatalogService service.
// All implementations must embed UnimplementedAdminCatalogServiceServer
// for forward compatibility.
type AdminCatalogServiceServer interface {
	ListK8SClusters(context.Context, *ListK8SClustersRequest) (*ListK8SClustersResponse, error)
	GetK8SCluster(context.Context, *GetK8SClusterRequest) (*AdminK8SClusterDetail, error)
	CreateK8SCluster(context.Context, *CreateK8SClusterRequest) (*AdminK8SClusterDetail, error)
	UpdateK8SCluster(context.Context, *UpdateK8SClusterRequest) (*AdminK8SClusterDetail, error)
	DeleteK8SCluster(context.Context, *DeleteK8SClusterRequest) (*DeleteK8SClusterResponse, error)
	RevalidateK8SCluster(context.Context, *RevalidateK8SClusterRequest) (*AdminK8SClusterDetail, error)
	ListResourceDefinitions(context.Context, *ListResourceDefinitionsRequest) (*ListResourceDefinitionsResponse, error)
	CreateResourceDefinition(context.Context, *CreateResourceDefinitionRequest) (*CreateResourceDefinitionResponse, error)
	ListResourceDefinitionZoneSupport(context.Context, *ListResourceDefinitionZoneSupportRequest) (*ListResourceDefinitionZoneSupportResponse, error)
	ReplaceResourceDefinitionZoneSupport(context.Context, *ReplaceResourceDefinitionZoneSupportRequest) (*ReplaceResourceDefinitionZoneSupportResponse, error)
	UpdateResourceDefinitionStatus(context.Context, *UpdateResourceDefinitionStatusRequest) (*AdminResourceDefinition, error)
	DeleteResourceDefinition(context.Context, *DeleteResourceDefinitionRequest) (*DeleteResourceDefinitionResponse, error)
	ListResourceTemplateCatalog(context.Context, *ListResourceTemplateCatalogRequest) (*ListResourceTemplateCatalogResponse, error)
	ListResourceTemplates(context.Context, *ListResourceTemplatesRequest) (*ListResourceTemplatesResponse, error)
	GetResourceTemplate(context.Context, *GetResourceTemplateRequest) (*AdminResourceTemplate, error)
	CreateResourceTemplate(context.Context, *CreateResourceTemplateRequest) (*AdminResourceTemplate, error)
	UpdateResourceTemplate(context.Context, *UpdateResourceTemplateRequest) (*AdminResourceTemplate, error)
	DeleteResourceTemplate(context.Context, *DeleteResourceTemplateRequest) (*DeleteResourceTemplateResponse, error)
	GetClusterNodesAdmin(context.Context, *GetClusterNodesAdminRequest) (*GetClusterNodesAdminResponse, error)
	mustEmbedUnimplementedAdminCatalogServiceServer()
}

// UnimplementedAdminCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdminCatalogServiceServer struct{}

func (UnimplementedAdminCatalogServiceServer) ListK8SClusters(context.Context, *ListK8SClustersRequest) (*ListK8SClustersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListK8SClusters not implemented")
}
func (UnimplementedAdminCatalogServiceServer) GetK8SCluster(context.Context, *GetK8SClusterRequest) (*AdminK8SClusterDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetK8SCluster not implemented")
}
func (UnimplementedAdminCatalogServiceServer) CreateK8SCluster(context.Context, *CreateK8SClusterRequest) (*AdminK8SClusterDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateK8SCluster not implemented")
}
func (UnimplementedAdminCatalogServiceServer) UpdateK8SCluster(context.Context, *UpdateK8SClusterRequest) (*AdminK8SClusterDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateK8SCluster not implemented")
}
func (UnimplementedAdminCatalogServiceServer) DeleteK8SCluster(context.Context, *DeleteK8SClusterRequest) (*DeleteK8SClusterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteK8SCluster not implemented")
}
func (UnimplementedAdminCatalogServiceServer) RevalidateK8SCluster(context.Context, *RevalidateK8SClusterRequest) (*AdminK8SClusterDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevalidateK8SCluster not implemented")
}
func (UnimplementedAdminCatalogServiceServer) ListResourceDefinitions(context.Context, *ListResourceDefinitionsRequest) (*ListResourceDefinitionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResourceDefinitions not implemented")
}
func (UnimplementedAdminCatalogServiceServer) CreateResourceDefinition(context.Context, *CreateResourceDefinitionRequest) (*CreateResourceDefinitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResourceDefinition not implemented")
}
func (UnimplementedAdminCatalogServiceServer) ListResourceDefinitionZoneSupport(context.Context, *ListResourceDefinitionZoneSupportRequest) (*ListResourceDefinitionZoneSupportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResourceDefinitionZoneSupport not implemented")
}
func (UnimplementedAdminCatalogServiceServer) ReplaceResourceDefinitionZoneSupport(context.Context, *ReplaceResourceDefinitionZoneSupportRequest) (*ReplaceResourceDefinitionZoneSupportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplaceResourceDefinitionZoneSupport not implemented")
}
func (UnimplementedAdminCatalogServiceServer) UpdateResourceDefinitionStatus(context.Context, *UpdateResourceDefinitionStatusRequest) (*AdminResourceDefinition, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateResourceDefinitionStatus not implemented")
}
func (UnimplementedAdminCatalogServiceServer) DeleteResourceDefinition(context.Context, *DeleteResourceDefinitionRequest) (*DeleteResourceDefinitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResourceDefinition not implemented")
}
func (UnimplementedAdminCatalogServiceServer) ListResourceTemplateCatalog(context.Context, *ListResourceTemplateCatalogRequest) (*ListResourceTemplateCatalogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResourceTemplateCatalog not implemented")
}
func (UnimplementedAdminCatalogServiceServer) ListResourceTemplates(context.Context, *ListResourceTemplatesRequest) (*ListResourceTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListResourceTemplates not implemented")
}
func (UnimplementedAdminCatalogServiceServer) GetResourceTemplate(context.Context, *GetResourceTemplateRequest) (*AdminResourceTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetResourceTemplate not implemented")
}
func (UnimplementedAdminCatalogServiceServer) CreateResourceTemplate(context.Context, *CreateResourceTemplateRequest) (*AdminResourceTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateResourceTemplate not implemented")
}
func (UnimplementedAdminCatalogServiceServer) UpdateResourceTemplate(context.Context, *UpdateResourceTemplateRequest) (*AdminResourceTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateResourceTemplate not implemented")
}
func (UnimplementedAdminCatalogServiceServer) DeleteResourceTemplate(context.Context, *DeleteResourceTemplateRequest) (*DeleteResourceTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteResourceTemplate not implemented")
}
func (UnimplementedAdminCatalogServiceServer) GetClusterNodesAdmin(context.Context, *GetClusterNodesAdminRequest) (*GetClusterNodesAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterNodesAdmin not implemented")
}
func (UnimplementedAdminCatalogServiceServer) mustEmbedUnimplementedAdminCatalogServiceServer() {}
func (UnimplementedAdminCatalogServiceServer) testEmbeddedByValue()                             {}

// UnsafeAdminCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminCatalogServiceServer will
// result in compilation errors.
type UnsafeAdminCatalogServiceServer interface {
	mustEmbedUnimplementedAdminCatalogServiceServer()
}

func RegisterAdminCatalogServiceServer(s grpc.ServiceRegistrar, srv AdminCatalogServiceServer) {
	// If the following call pancis, it indicates UnimplementedAdminCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdminCatalogService_ServiceDesc, srv)
}

func _AdminCatalogService_ListK8SClusters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListK8SClustersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).ListK8SClusters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_ListK8SClusters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).ListK8SClusters(ctx, req.(*ListK8SClustersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_GetK8SCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetK8SClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).GetK8SCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_GetK8SCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).GetK8SCluster(ctx, req.(*GetK8SClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_CreateK8SCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateK8SClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).CreateK8SCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_CreateK8SCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).CreateK8SCluster(ctx, req.(*CreateK8SClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_UpdateK8SCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateK8SClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).UpdateK8SCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_UpdateK8SCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).UpdateK8SCluster(ctx, req.(*UpdateK8SClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_DeleteK8SCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteK8SClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).DeleteK8SCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_DeleteK8SCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).DeleteK8SCluster(ctx, req.(*DeleteK8SClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_RevalidateK8SCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevalidateK8SClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).RevalidateK8SCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_RevalidateK8SCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).RevalidateK8SCluster(ctx, req.(*RevalidateK8SClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_ListResourceDefinitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourceDefinitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).ListResourceDefinitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_ListResourceDefinitions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).ListResourceDefinitions(ctx, req.(*ListResourceDefinitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_CreateResourceDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).CreateResourceDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_CreateResourceDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).CreateResourceDefinition(ctx, req.(*CreateResourceDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_ListResourceDefinitionZoneSupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourceDefinitionZoneSupportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).ListResourceDefinitionZoneSupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_ListResourceDefinitionZoneSupport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).ListResourceDefinitionZoneSupport(ctx, req.(*ListResourceDefinitionZoneSupportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_ReplaceResourceDefinitionZoneSupport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceResourceDefinitionZoneSupportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).ReplaceResourceDefinitionZoneSupport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_ReplaceResourceDefinitionZoneSupport_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).ReplaceResourceDefinitionZoneSupport(ctx, req.(*ReplaceResourceDefinitionZoneSupportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_UpdateResourceDefinitionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateResourceDefinitionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).UpdateResourceDefinitionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_UpdateResourceDefinitionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).UpdateResourceDefinitionStatus(ctx, req.(*UpdateResourceDefinitionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_DeleteResourceDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).DeleteResourceDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_DeleteResourceDefinition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).DeleteResourceDefinition(ctx, req.(*DeleteResourceDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_ListResourceTemplateCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourceTemplateCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).ListResourceTemplateCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_ListResourceTemplateCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).ListResourceTemplateCatalog(ctx, req.(*ListResourceTemplateCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_ListResourceTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourceTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).ListResourceTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_ListResourceTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).ListResourceTemplates(ctx, req.(*ListResourceTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_GetResourceTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResourceTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).GetResourceTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_GetResourceTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).GetResourceTemplate(ctx, req.(*GetResourceTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_CreateResourceTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateResourceTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).CreateResourceTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_CreateResourceTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).CreateResourceTemplate(ctx, req.(*CreateResourceTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_UpdateResourceTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateResourceTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).UpdateResourceTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_UpdateResourceTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).UpdateResourceTemplate(ctx, req.(*UpdateResourceTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_DeleteResourceTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).DeleteResourceTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_DeleteResourceTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).DeleteResourceTemplate(ctx, req.(*DeleteResourceTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminCatalogService_GetClusterNodesAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterNodesAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminCatalogServiceServer).GetClusterNodesAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminCatalogService_GetClusterNodesAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminCatalogServiceServer).GetClusterNodesAdmin(ctx, req.(*GetClusterNodesAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminCatalogService_ServiceDesc is the grpc.ServiceDesc for AdminCatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminCatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "resourceplatform.admin.AdminCatalogService",
	HandlerType: (*AdminCatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListK8sClusters",
			Handler:    _AdminCatalogService_ListK8SClusters_Handler,
		},
		{
			MethodName: "GetK8sCluster",
			Handler:    _AdminCatalogService_GetK8SCluster_Handler,
		},
		{
			MethodName: "CreateK8sCluster",
			Handler:    _AdminCatalogService_CreateK8SCluster_Handler,
		},
		{
			MethodName: "UpdateK8sCluster",
			Handler:    _AdminCatalogService_UpdateK8SCluster_Handler,
		},
		{
			MethodName: "DeleteK8sCluster",
			Handler:    _AdminCatalogService_DeleteK8SCluster_Handler,
		},
		{
			MethodName: "RevalidateK8sCluster",
			Handler:    _AdminCatalogService_RevalidateK8SCluster_Handler,
		},
		{
			MethodName: "ListResourceDefinitions",
			Handler:    _AdminCatalogService_ListResourceDefinitions_Handler,
		},
		{
			MethodName: "CreateResourceDefinition",
			Handler:    _AdminCatalogService_CreateResourceDefinition_Handler,
		},
		{
			MethodName: "ListResourceDefinitionZoneSupport",
			Handler:    _AdminCatalogService_ListResourceDefinitionZoneSupport_Handler,
		},
		{
			MethodName: "ReplaceResourceDefinitionZoneSupport",
			Handler:    _AdminCatalogService_ReplaceResourceDefinitionZoneSupport_Handler,
		},
		{
			MethodName: "UpdateResourceDefinitionStatus",
			Handler:    _AdminCatalogService_UpdateResourceDefinitionStatus_Handler,
		},
		{
			MethodName: "DeleteResourceDefinition",
			Handler:    _AdminCatalogService_DeleteResourceDefinition_Handler,
		},
		{
			MethodName: "ListResourceTemplateCatalog",
			Handler:    _AdminCatalogService_ListResourceTemplateCatalog_Handler,
		},
		{
			MethodName: "ListResourceTemplates",
			Handler:    _AdminCatalogService_ListResourceTemplates_Handler,
		},
		{
			MethodName: "GetResourceTemplate",
			Handler:    _AdminCatalogService_GetResourceTemplate_Handler,
		},
		{
			MethodName: "CreateResourceTemplate",
			Handler:    _AdminCatalogService_CreateResourceTemplate_Handler,
		},
		{
			MethodName: "UpdateResourceTemplate",
			Handler:    _AdminCatalogService_UpdateResourceTemplate_Handler,
		},
		{
			MethodName: "DeleteResourceTemplate",
			Handler:    _AdminCatalogService_DeleteResourceTemplate_Handler,
		},
		{
			MethodName: "GetClusterNodesAdmin",
			Handler:    _AdminCatalogService_GetClusterNodesAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "resourceplatform_admin.proto",
}
