// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: resourceplatform_admin.proto

package controlplanegrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminK8SClusterListItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ZoneName          string                 `protobuf:"bytes,4,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	ApiServerUrl      string                 `protobuf:"bytes,5,opt,name=api_server_url,json=apiServerUrl,proto3" json:"api_server_url,omitempty"`
	KubernetesVersion string                 `protobuf:"bytes,6,opt,name=kubernetes_version,json=kubernetesVersion,proto3" json:"kubernetes_version,omitempty"`
	ValidationStatus  string                 `protobuf:"bytes,7,opt,name=validation_status,json=validationStatus,proto3" json:"validation_status,omitempty"`
	LastValidatedAt   string                 `protobuf:"bytes,8,opt,name=last_validated_at,json=lastValidatedAt,proto3" json:"last_validated_at,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdminK8SClusterListItem) Reset() {
	*x = AdminK8SClusterListItem{}
	mi := &file_resourceplatform_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminK8SClusterListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminK8SClusterListItem) ProtoMessage() {}

func (x *AdminK8SClusterListItem) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminK8SClusterListItem.ProtoReflect.Descriptor instead.
func (*AdminK8SClusterListItem) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{0}
}

func (x *AdminK8SClusterListItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminK8SClusterListItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminK8SClusterListItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminK8SClusterListItem) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *AdminK8SClusterListItem) GetApiServerUrl() string {
	if x != nil {
		return x.ApiServerUrl
	}
	return ""
}

func (x *AdminK8SClusterListItem) GetKubernetesVersion() string {
	if x != nil {
		return x.KubernetesVersion
	}
	return ""
}

func (x *AdminK8SClusterListItem) GetValidationStatus() string {
	if x != nil {
		return x.ValidationStatus
	}
	return ""
}

func (x *AdminK8SClusterListItem) GetLastValidatedAt() string {
	if x != nil {
		return x.LastValidatedAt
	}
	return ""
}

func (x *AdminK8SClusterListItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AdminK8SClusterDetail struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description       string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ZoneId            string                 `protobuf:"bytes,4,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	ZoneName          string                 `protobuf:"bytes,5,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	ApiServerUrl      string                 `protobuf:"bytes,6,opt,name=api_server_url,json=apiServerUrl,proto3" json:"api_server_url,omitempty"`
	CurrentContext    string                 `protobuf:"bytes,7,opt,name=current_context,json=currentContext,proto3" json:"current_context,omitempty"`
	KubernetesVersion string                 `protobuf:"bytes,8,opt,name=kubernetes_version,json=kubernetesVersion,proto3" json:"kubernetes_version,omitempty"`
	ValidationStatus  string                 `protobuf:"bytes,9,opt,name=validation_status,json=validationStatus,proto3" json:"validation_status,omitempty"`
	LastValidatedAt   string                 `protobuf:"bytes,10,opt,name=last_validated_at,json=lastValidatedAt,proto3" json:"last_validated_at,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AdminK8SClusterDetail) Reset() {
	*x = AdminK8SClusterDetail{}
	mi := &file_resourceplatform_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminK8SClusterDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminK8SClusterDetail) ProtoMessage() {}

func (x *AdminK8SClusterDetail) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminK8SClusterDetail.ProtoReflect.Descriptor instead.
func (*AdminK8SClusterDetail) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{1}
}

func (x *AdminK8SClusterDetail) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminK8SClusterDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminK8SClusterDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminK8SClusterDetail) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *AdminK8SClusterDetail) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *AdminK8SClusterDetail) GetApiServerUrl() string {
	if x != nil {
		return x.ApiServerUrl
	}
	return ""
}

func (x *AdminK8SClusterDetail) GetCurrentContext() string {
	if x != nil {
		return x.CurrentContext
	}
	return ""
}

func (x *AdminK8SClusterDetail) GetKubernetesVersion() string {
	if x != nil {
		return x.KubernetesVersion
	}
	return ""
}

func (x *AdminK8SClusterDetail) GetValidationStatus() string {
	if x != nil {
		return x.ValidationStatus
	}
	return ""
}

func (x *AdminK8SClusterDetail) GetLastValidatedAt() string {
	if x != nil {
		return x.LastValidatedAt
	}
	return ""
}

func (x *AdminK8SClusterDetail) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type AdminResourceDefinition struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResourceType    string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceVersion string                 `protobuf:"bytes,3,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	ResourceModel   string                 `protobuf:"bytes,4,opt,name=resource_model,json=resourceModel,proto3" json:"resource_model,omitempty"`
	DisplayName     string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Status          string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	ResourceCount   int32                  `protobuf:"varint,7,opt,name=resource_count,json=resourceCount,proto3" json:"resource_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AdminResourceDefinition) Reset() {
	*x = AdminResourceDefinition{}
	mi := &file_resourceplatform_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResourceDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResourceDefinition) ProtoMessage() {}

func (x *AdminResourceDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResourceDefinition.ProtoReflect.Descriptor instead.
func (*AdminResourceDefinition) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AdminResourceDefinition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminResourceDefinition) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AdminResourceDefinition) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *AdminResourceDefinition) GetResourceModel() string {
	if x != nil {
		return x.ResourceModel
	}
	return ""
}

func (x *AdminResourceDefinition) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AdminResourceDefinition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdminResourceDefinition) GetResourceCount() int32 {
	if x != nil {
		return x.ResourceCount
	}
	return 0
}

type AdminResourceTemplate struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ResourceDefinitionId string                 `protobuf:"bytes,2,opt,name=resource_definition_id,json=resourceDefinitionId,proto3" json:"resource_definition_id,omitempty"`
	ResourceType         string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ModelName            string                 `protobuf:"bytes,4,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ResourceVersion      string                 `protobuf:"bytes,5,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	ResourceModel        string                 `protobuf:"bytes,6,opt,name=resource_model,json=resourceModel,proto3" json:"resource_model,omitempty"`
	Name                 string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	StreamKey            string                 `protobuf:"bytes,9,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	ConsumerGroup        string                 `protobuf:"bytes,10,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	TemplateBody         string                 `protobuf:"bytes,11,opt,name=template_body,json=templateBody,proto3" json:"template_body,omitempty"`
	YamlValid            bool                   `protobuf:"varint,12,opt,name=yaml_valid,json=yamlValid,proto3" json:"yaml_valid,omitempty"`
	CreatedAt            string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string                 `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AdminResourceTemplate) Reset() {
	*x = AdminResourceTemplate{}
	mi := &file_resourceplatform_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResourceTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResourceTemplate) ProtoMessage() {}

func (x *AdminResourceTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResourceTemplate.ProtoReflect.Descriptor instead.
func (*AdminResourceTemplate) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminResourceTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AdminResourceTemplate) GetResourceDefinitionId() string {
	if x != nil {
		return x.ResourceDefinitionId
	}
	return ""
}

func (x *AdminResourceTemplate) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AdminResourceTemplate) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *AdminResourceTemplate) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *AdminResourceTemplate) GetResourceModel() string {
	if x != nil {
		return x.ResourceModel
	}
	return ""
}

func (x *AdminResourceTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminResourceTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminResourceTemplate) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *AdminResourceTemplate) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *AdminResourceTemplate) GetTemplateBody() string {
	if x != nil {
		return x.TemplateBody
	}
	return ""
}

func (x *AdminResourceTemplate) GetYamlValid() bool {
	if x != nil {
		return x.YamlValid
	}
	return false
}

func (x *AdminResourceTemplate) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *AdminResourceTemplate) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type AdminK8SClusterNode struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Roles            []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	KubeletVersion   string                 `protobuf:"bytes,3,opt,name=kubelet_version,json=kubeletVersion,proto3" json:"kubelet_version,omitempty"`
	ContainerRuntime string                 `protobuf:"bytes,4,opt,name=container_runtime,json=containerRuntime,proto3" json:"container_runtime,omitempty"`
	OsImage          string                 `protobuf:"bytes,5,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`
	KernelVersion    string                 `protobuf:"bytes,6,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	Ready            bool                   `protobuf:"varint,7,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdminK8SClusterNode) Reset() {
	*x = AdminK8SClusterNode{}
	mi := &file_resourceplatform_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminK8SClusterNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminK8SClusterNode) ProtoMessage() {}

func (x *AdminK8SClusterNode) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminK8SClusterNode.ProtoReflect.Descriptor instead.
func (*AdminK8SClusterNode) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{4}
}

func (x *AdminK8SClusterNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminK8SClusterNode) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AdminK8SClusterNode) GetKubeletVersion() string {
	if x != nil {
		return x.KubeletVersion
	}
	return ""
}

func (x *AdminK8SClusterNode) GetContainerRuntime() string {
	if x != nil {
		return x.ContainerRuntime
	}
	return ""
}

func (x *AdminK8SClusterNode) GetOsImage() string {
	if x != nil {
		return x.OsImage
	}
	return ""
}

func (x *AdminK8SClusterNode) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *AdminK8SClusterNode) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type ListK8SClustersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListK8SClustersRequest) Reset() {
	*x = ListK8SClustersRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListK8SClustersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListK8SClustersRequest) ProtoMessage() {}

func (x *ListK8SClustersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListK8SClustersRequest.ProtoReflect.Descriptor instead.
func (*ListK8SClustersRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{5}
}

type ListK8SClustersResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Items         []*AdminK8SClusterListItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListK8SClustersResponse) Reset() {
	*x = ListK8SClustersResponse{}
	mi := &file_resourceplatform_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListK8SClustersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListK8SClustersResponse) ProtoMessage() {}

func (x *ListK8SClustersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListK8SClustersResponse.ProtoReflect.Descriptor instead.
func (*ListK8SClustersResponse) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{6}
}

func (x *ListK8SClustersResponse) GetItems() []*AdminK8SClusterListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetK8SClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetK8SClusterRequest) Reset() {
	*x = GetK8SClusterRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetK8SClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetK8SClusterRequest) ProtoMessage() {}

func (x *GetK8SClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetK8SClusterRequest.ProtoReflect.Descriptor instead.
func (*GetK8SClusterRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetK8SClusterRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type CreateK8SClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ZoneId        string                 `protobuf:"bytes,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Kubeconfig    []byte                 `protobuf:"bytes,4,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateK8SClusterRequest) Reset() {
	*x = CreateK8SClusterRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateK8SClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateK8SClusterRequest) ProtoMessage() {}

func (x *CreateK8SClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateK8SClusterRequest.ProtoReflect.Descriptor instead.
func (*CreateK8SClusterRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{8}
}

func (x *CreateK8SClusterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateK8SClusterRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateK8SClusterRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *CreateK8SClusterRequest) GetKubeconfig() []byte {
	if x != nil {
		return x.Kubeconfig
	}
	return nil
}

type UpdateK8SClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ZoneId        string                 `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Kubeconfig    []byte                 `protobuf:"bytes,3,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateK8SClusterRequest) Reset() {
	*x = UpdateK8SClusterRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateK8SClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateK8SClusterRequest) ProtoMessage() {}

func (x *UpdateK8SClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateK8SClusterRequest.ProtoReflect.Descriptor instead.
func (*UpdateK8SClusterRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateK8SClusterRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *UpdateK8SClusterRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *UpdateK8SClusterRequest) GetKubeconfig() []byte {
	if x != nil {
		return x.Kubeconfig
	}
	return nil
}

type DeleteK8SClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteK8SClusterRequest) Reset() {
	*x = DeleteK8SClusterRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteK8SClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteK8SClusterRequest) ProtoMessage() {}

func (x *DeleteK8SClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteK8SClusterRequest.ProtoReflect.Descriptor instead.
func (*DeleteK8SClusterRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteK8SClusterRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type DeleteK8SClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteK8SClusterResponse) Reset() {
	*x = DeleteK8SClusterResponse{}
	mi := &file_resourceplatform_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteK8SClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteK8SClusterResponse) ProtoMessage() {}

func (x *DeleteK8SClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteK8SClusterResponse.ProtoReflect.Descriptor instead.
func (*DeleteK8SClusterResponse) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteK8SClusterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RevalidateK8SClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevalidateK8SClusterRequest) Reset() {
	*x = RevalidateK8SClusterRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevalidateK8SClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevalidateK8SClusterRequest) ProtoMessage() {}

func (x *RevalidateK8SClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevalidateK8SClusterRequest.ProtoReflect.Descriptor instead.
func (*RevalidateK8SClusterRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{12}
}

func (x *RevalidateK8SClusterRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type ListResourceDefinitionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceDefinitionsRequest) Reset() {
	*x = ListResourceDefinitionsRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceDefinitionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceDefinitionsRequest) ProtoMessage() {}

func (x *ListResourceDefinitionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceDefinitionsRequest.ProtoReflect.Descriptor instead.
func (*ListResourceDefinitionsRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{13}
}

type ListResourceDefinitionsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Items         []*AdminResourceDefinition `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceDefinitionsResponse) Reset() {
	*x = ListResourceDefinitionsResponse{}
	mi := &file_resourceplatform_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceDefinitionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceDefinitionsResponse) ProtoMessage() {}

func (x *ListResourceDefinitionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceDefinitionsResponse.ProtoReflect.Descriptor instead.
func (*ListResourceDefinitionsResponse) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{14}
}

func (x *ListResourceDefinitionsResponse) GetItems() []*AdminResourceDefinition {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateResourceDefinitionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResourceType    string                 `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceModel   string                 `protobuf:"bytes,2,opt,name=resource_model,json=resourceModel,proto3" json:"resource_model,omitempty"`
	ResourceVersion string                 `protobuf:"bytes,3,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	DisplayName     string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateResourceDefinitionRequest) Reset() {
	*x = CreateResourceDefinitionRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceDefinitionRequest) ProtoMessage() {}

func (x *CreateResourceDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceDefinitionRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{15}
}

func (x *CreateResourceDefinitionRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *CreateResourceDefinitionRequest) GetResourceModel() string {
	if x != nil {
		return x.ResourceModel
	}
	return ""
}

func (x *CreateResourceDefinitionRequest) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *CreateResourceDefinitionRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type CreateResourceDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResourceDefinitionResponse) Reset() {
	*x = CreateResourceDefinitionResponse{}
	mi := &file_resourceplatform_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceDefinitionResponse) ProtoMessage() {}

func (x *CreateResourceDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceDefinitionResponse.ProtoReflect.Descriptor instead.
func (*CreateResourceDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{16}
}

func (x *CreateResourceDefinitionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AdminResourceDefinitionZoneSupport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneId        string                 `protobuf:"bytes,1,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	ZoneName      string                 `protobuf:"bytes,2,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminResourceDefinitionZoneSupport) Reset() {
	*x = AdminResourceDefinitionZoneSupport{}
	mi := &file_resourceplatform_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminResourceDefinitionZoneSupport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminResourceDefinitionZoneSupport) ProtoMessage() {}

func (x *AdminResourceDefinitionZoneSupport) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminResourceDefinitionZoneSupport.ProtoReflect.Descriptor instead.
func (*AdminResourceDefinitionZoneSupport) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{17}
}

func (x *AdminResourceDefinitionZoneSupport) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *AdminResourceDefinitionZoneSupport) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *AdminResourceDefinitionZoneSupport) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ListResourceDefinitionZoneSupportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefinitionId  string                 `protobuf:"bytes,1,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceDefinitionZoneSupportRequest) Reset() {
	*x = ListResourceDefinitionZoneSupportRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceDefinitionZoneSupportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceDefinitionZoneSupportRequest) ProtoMessage() {}

func (x *ListResourceDefinitionZoneSupportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceDefinitionZoneSupportRequest.ProtoReflect.Descriptor instead.
func (*ListResourceDefinitionZoneSupportRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{18}
}

func (x *ListResourceDefinitionZoneSupportRequest) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

type ListResourceDefinitionZoneSupportResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Items         []*AdminResourceDefinitionZoneSupport `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceDefinitionZoneSupportResponse) Reset() {
	*x = ListResourceDefinitionZoneSupportResponse{}
	mi := &file_resourceplatform_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceDefinitionZoneSupportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceDefinitionZoneSupportResponse) ProtoMessage() {}

func (x *ListResourceDefinitionZoneSupportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceDefinitionZoneSupportResponse.ProtoReflect.Descriptor instead.
func (*ListResourceDefinitionZoneSupportResponse) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{19}
}

func (x *ListResourceDefinitionZoneSupportResponse) GetItems() []*AdminResourceDefinitionZoneSupport {
	if x != nil {
		return x.Items
	}
	return nil
}

type ReplaceResourceDefinitionZoneSupportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefinitionId  string                 `protobuf:"bytes,1,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	ZoneIds       []string               `protobuf:"bytes,2,rep,name=zone_ids,json=zoneIds,proto3" json:"zone_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceResourceDefinitionZoneSupportRequest) Reset() {
	*x = ReplaceResourceDefinitionZoneSupportRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceResourceDefinitionZoneSupportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceResourceDefinitionZoneSupportRequest) ProtoMessage() {}

func (x *ReplaceResourceDefinitionZoneSupportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceResourceDefinitionZoneSupportRequest.ProtoReflect.Descriptor instead.
func (*ReplaceResourceDefinitionZoneSupportRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ReplaceResourceDefinitionZoneSupportRequest) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

func (x *ReplaceResourceDefinitionZoneSupportRequest) GetZoneIds() []string {
	if x != nil {
		return x.ZoneIds
	}
	return nil
}

type ReplaceResourceDefinitionZoneSupportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceResourceDefinitionZoneSupportResponse) Reset() {
	*x = ReplaceResourceDefinitionZoneSupportResponse{}
	mi := &file_resourceplatform_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceResourceDefinitionZoneSupportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceResourceDefinitionZoneSupportResponse) ProtoMessage() {}

func (x *ReplaceResourceDefinitionZoneSupportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceResourceDefinitionZoneSupportResponse.ProtoReflect.Descriptor instead.
func (*ReplaceResourceDefinitionZoneSupportResponse) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{21}
}

func (x *ReplaceResourceDefinitionZoneSupportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteResourceDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefinitionId  string                 `protobuf:"bytes,1,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceDefinitionRequest) Reset() {
	*x = DeleteResourceDefinitionRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceDefinitionRequest) ProtoMessage() {}

func (x *DeleteResourceDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceDefinitionRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteResourceDefinitionRequest) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

type DeleteResourceDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceDefinitionResponse) Reset() {
	*x = DeleteResourceDefinitionResponse{}
	mi := &file_resourceplatform_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceDefinitionResponse) ProtoMessage() {}

func (x *DeleteResourceDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceDefinitionResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{23}
}

type UpdateResourceDefinitionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DefinitionId  string                 `protobuf:"bytes,1,opt,name=definition_id,json=definitionId,proto3" json:"definition_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResourceDefinitionStatusRequest) Reset() {
	*x = UpdateResourceDefinitionStatusRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceDefinitionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceDefinitionStatusRequest) ProtoMessage() {}

func (x *UpdateResourceDefinitionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceDefinitionStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceDefinitionStatusRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateResourceDefinitionStatusRequest) GetDefinitionId() string {
	if x != nil {
		return x.DefinitionId
	}
	return ""
}

func (x *UpdateResourceDefinitionStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListResourceTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceTemplatesRequest) Reset() {
	*x = ListResourceTemplatesRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceTemplatesRequest) ProtoMessage() {}

func (x *ListResourceTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListResourceTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{25}
}

type ListResourceTemplatesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*AdminResourceTemplate `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceTemplatesResponse) Reset() {
	*x = ListResourceTemplatesResponse{}
	mi := &file_resourceplatform_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceTemplatesResponse) ProtoMessage() {}

func (x *ListResourceTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListResourceTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{26}
}

func (x *ListResourceTemplatesResponse) GetItems() []*AdminResourceTemplate {
	if x != nil {
		return x.Items
	}
	return nil
}

type ListResourceTemplateCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceTemplateCatalogRequest) Reset() {
	*x = ListResourceTemplateCatalogRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceTemplateCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceTemplateCatalogRequest) ProtoMessage() {}

func (x *ListResourceTemplateCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceTemplateCatalogRequest.ProtoReflect.Descriptor instead.
func (*ListResourceTemplateCatalogRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{27}
}

type ListResourceTemplateCatalogResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Items         []*AdminResourceTemplate `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourceTemplateCatalogResponse) Reset() {
	*x = ListResourceTemplateCatalogResponse{}
	mi := &file_resourceplatform_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourceTemplateCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourceTemplateCatalogResponse) ProtoMessage() {}

func (x *ListResourceTemplateCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourceTemplateCatalogResponse.ProtoReflect.Descriptor instead.
func (*ListResourceTemplateCatalogResponse) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{28}
}

func (x *ListResourceTemplateCatalogResponse) GetItems() []*AdminResourceTemplate {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetResourceTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceTemplateRequest) Reset() {
	*x = GetResourceTemplateRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceTemplateRequest) ProtoMessage() {}

func (x *GetResourceTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetResourceTemplateRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{29}
}

func (x *GetResourceTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type CreateResourceTemplateRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ResourceDefinitionId string                 `protobuf:"bytes,1,opt,name=resource_definition_id,json=resourceDefinitionId,proto3" json:"resource_definition_id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	StreamKey            string                 `protobuf:"bytes,4,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	ConsumerGroup        string                 `protobuf:"bytes,5,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	TemplateBody         string                 `protobuf:"bytes,6,opt,name=template_body,json=templateBody,proto3" json:"template_body,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateResourceTemplateRequest) Reset() {
	*x = CreateResourceTemplateRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResourceTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceTemplateRequest) ProtoMessage() {}

func (x *CreateResourceTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceTemplateRequest.ProtoReflect.Descriptor instead.
func (*CreateResourceTemplateRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{30}
}

func (x *CreateResourceTemplateRequest) GetResourceDefinitionId() string {
	if x != nil {
		return x.ResourceDefinitionId
	}
	return ""
}

func (x *CreateResourceTemplateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateResourceTemplateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateResourceTemplateRequest) GetStreamKey() string {
	if x != nil {
		return x.StreamKey
	}
	return ""
}

func (x *CreateResourceTemplateRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *CreateResourceTemplateRequest) GetTemplateBody() string {
	if x != nil {
		return x.TemplateBody
	}
	return ""
}

type UpdateResourceTemplateRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TemplateId           string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	ResourceDefinitionId *string                `protobuf:"bytes,2,opt,name=resource_definition_id,json=resourceDefinitionId,proto3,oneof" json:"resource_definition_id,omitempty"`
	Name                 *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description          *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	StreamKey            *string                `protobuf:"bytes,5,opt,name=stream_key,json=streamKey,proto3,oneof" json:"stream_key,omitempty"`
	ConsumerGroup        *string                `protobuf:"bytes,6,opt,name=consumer_group,json=consumerGroup,proto3,oneof" json:"consumer_group,omitempty"`
	TemplateBody         *string                `protobuf:"bytes,7,opt,name=template_body,json=templateBody,proto3,oneof" json:"template_body,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateResourceTemplateRequest) Reset() {
	*x = UpdateResourceTemplateRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResourceTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceTemplateRequest) ProtoMessage() {}

func (x *UpdateResourceTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpdateResourceTemplateRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateResourceTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *UpdateResourceTemplateRequest) GetResourceDefinitionId() string {
	if x != nil && x.ResourceDefinitionId != nil {
		return *x.ResourceDefinitionId
	}
	return ""
}

func (x *UpdateResourceTemplateRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateResourceTemplateRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateResourceTemplateRequest) GetStreamKey() string {
	if x != nil && x.StreamKey != nil {
		return *x.StreamKey
	}
	return ""
}

func (x *UpdateResourceTemplateRequest) GetConsumerGroup() string {
	if x != nil && x.ConsumerGroup != nil {
		return *x.ConsumerGroup
	}
	return ""
}

func (x *UpdateResourceTemplateRequest) GetTemplateBody() string {
	if x != nil && x.TemplateBody != nil {
		return *x.TemplateBody
	}
	return ""
}

type DeleteResourceTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    string                 `protobuf:"bytes,1,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceTemplateRequest) Reset() {
	*x = DeleteResourceTemplateRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceTemplateRequest) ProtoMessage() {}

func (x *DeleteResourceTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceTemplateRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{32}
}

func (x *DeleteResourceTemplateRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type DeleteResourceTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceTemplateResponse) Reset() {
	*x = DeleteResourceTemplateResponse{}
	mi := &file_resourceplatform_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceTemplateResponse) ProtoMessage() {}

func (x *DeleteResourceTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceTemplateResponse) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{33}
}

type GetClusterNodesAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterNodesAdminRequest) Reset() {
	*x = GetClusterNodesAdminRequest{}
	mi := &file_resourceplatform_admin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterNodesAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterNodesAdminRequest) ProtoMessage() {}

func (x *GetClusterNodesAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterNodesAdminRequest.ProtoReflect.Descriptor instead.
func (*GetClusterNodesAdminRequest) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{34}
}

func (x *GetClusterNodesAdminRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type GetClusterNodesAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*AdminK8SClusterNode `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterNodesAdminResponse) Reset() {
	*x = GetClusterNodesAdminResponse{}
	mi := &file_resourceplatform_admin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterNodesAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterNodesAdminResponse) ProtoMessage() {}

func (x *GetClusterNodesAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resourceplatform_admin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterNodesAdminResponse.ProtoReflect.Descriptor instead.
func (*GetClusterNodesAdminResponse) Descriptor() ([]byte, []int) {
	return file_resourceplatform_admin_proto_rawDescGZIP(), []int{35}
}

func (x *GetClusterNodesAdminResponse) GetItems() []*AdminK8SClusterNode {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_resourceplatform_admin_proto protoreflect.FileDescriptor

const file_resourceplatform_admin_proto_rawDesc = "" +
	"\n" +
	"\x1cresourceplatform_admin.proto\x12\x16resourceplatform.admin\"\xc9\x02\n" +
	"\x17AdminK8sClusterListItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\tzone_name\x18\x04 \x01(\tR\bzoneName\x12$\n" +
	"\x0eapi_server_url\x18\x05 \x01(\tR\fapiServerUrl\x12-\n" +
	"\x12kubernetes_version\x18\x06 \x01(\tR\x11kubernetesVersion\x12+\n" +
	"\x11validation_status\x18\a \x01(\tR\x10validationStatus\x12*\n" +
	"\x11last_validated_at\x18\b \x01(\tR\x0flastValidatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"\x89\x03\n" +
	"\x15AdminK8sClusterDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x17\n" +
	"\azone_id\x18\x04 \x01(\tR\x06zoneId\x12\x1b\n" +
	"\tzone_name\x18\x05 \x01(\tR\bzoneName\x12$\n" +
	"\x0eapi_server_url\x18\x06 \x01(\tR\fapiServerUrl\x12'\n" +
	"\x0fcurrent_context\x18\a \x01(\tR\x0ecurrentContext\x12-\n" +
	"\x12kubernetes_version\x18\b \x01(\tR\x11kubernetesVersion\x12+\n" +
	"\x11validation_status\x18\t \x01(\tR\x10validationStatus\x12*\n" +
	"\x11last_validated_at\x18\n" +
	" \x01(\tR\x0flastValidatedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\"\x82\x02\n" +
	"\x17AdminResourceDefinition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\x12)\n" +
	"\x10resource_version\x18\x03 \x01(\tR\x0fresourceVersion\x12%\n" +
	"\x0eresource_model\x18\x04 \x01(\tR\rresourceModel\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0eresource_count\x18\a \x01(\x05R\rresourceCount\"\xf1\x03\n" +
	"\x15AdminResourceTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\x16resource_definition_id\x18\x02 \x01(\tR\x14resourceDefinitionId\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\x12\x1d\n" +
	"\n" +
	"model_name\x18\x04 \x01(\tR\tmodelName\x12)\n" +
	"\x10resource_version\x18\x05 \x01(\tR\x0fresourceVersion\x12%\n" +
	"\x0eresource_model\x18\x06 \x01(\tR\rresourceModel\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"stream_key\x18\t \x01(\tR\tstreamKey\x12%\n" +
	"\x0econsumer_group\x18\n" +
	" \x01(\tR\rconsumerGroup\x12#\n" +
	"\rtemplate_body\x18\v \x01(\tR\ftemplateBody\x12\x1d\n" +
	"\n" +
	"yaml_valid\x18\f \x01(\bR\tyamlValid\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\tR\tupdatedAt\"\xed\x01\n" +
	"\x13AdminK8sClusterNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x12'\n" +
	"\x0fkubelet_version\x18\x03 \x01(\tR\x0ekubeletVersion\x12+\n" +
	"\x11container_runtime\x18\x04 \x01(\tR\x10containerRuntime\x12\x19\n" +
	"\bos_image\x18\x05 \x01(\tR\aosImage\x12%\n" +
	"\x0ekernel_version\x18\x06 \x01(\tR\rkernelVersion\x12\x14\n" +
	"\x05ready\x18\a \x01(\bR\x05ready\"\x18\n" +
	"\x16ListK8sClustersRequest\"`\n" +
	"\x17ListK8sClustersResponse\x12E\n" +
	"\x05items\x18\x01 \x03(\v2/.resourceplatform.admin.AdminK8sClusterListItemR\x05items\"5\n" +
	"\x14GetK8sClusterRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"\x88\x01\n" +
	"\x17CreateK8sClusterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x17\n" +
	"\azone_id\x18\x03 \x01(\tR\x06zoneId\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x04 \x01(\fR\n" +
	"kubeconfig\"q\n" +
	"\x17UpdateK8sClusterRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\azone_id\x18\x02 \x01(\tR\x06zoneId\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x03 \x01(\fR\n" +
	"kubeconfig\"8\n" +
	"\x17DeleteK8sClusterRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"4\n" +
	"\x18DeleteK8sClusterResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"<\n" +
	"\x1bRevalidateK8sClusterRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\" \n" +
	"\x1eListResourceDefinitionsRequest\"h\n" +
	"\x1fListResourceDefinitionsResponse\x12E\n" +
	"\x05items\x18\x01 \x03(\v2/.resourceplatform.admin.AdminResourceDefinitionR\x05items\"\xbb\x01\n" +
	"\x1fCreateResourceDefinitionRequest\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12%\n" +
	"\x0eresource_model\x18\x02 \x01(\tR\rresourceModel\x12)\n" +
	"\x10resource_version\x18\x03 \x01(\tR\x0fresourceVersion\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\"<\n" +
	" CreateResourceDefinitionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"t\n" +
	"\"AdminResourceDefinitionZoneSupport\x12\x17\n" +
	"\azone_id\x18\x01 \x01(\tR\x06zoneId\x12\x1b\n" +
	"\tzone_name\x18\x02 \x01(\tR\bzoneName\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"O\n" +
	"(ListResourceDefinitionZoneSupportRequest\x12#\n" +
	"\rdefinition_id\x18\x01 \x01(\tR\fdefinitionId\"}\n" +
	")ListResourceDefinitionZoneSupportResponse\x12P\n" +
	"\x05items\x18\x01 \x03(\v2:.resourceplatform.admin.AdminResourceDefinitionZoneSupportR\x05items\"m\n" +
	"+ReplaceResourceDefinitionZoneSupportRequest\x12#\n" +
	"\rdefinition_id\x18\x01 \x01(\tR\fdefinitionId\x12\x19\n" +
	"\bzone_ids\x18\x02 \x03(\tR\azoneIds\"H\n" +
	",ReplaceResourceDefinitionZoneSupportResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"F\n" +
	"\x1fDeleteResourceDefinitionRequest\x12#\n" +
	"\rdefinition_id\x18\x01 \x01(\tR\fdefinitionId\"\"\n" +
	" DeleteResourceDefinitionResponse\"d\n" +
	"%UpdateResourceDefinitionStatusRequest\x12#\n" +
	"\rdefinition_id\x18\x01 \x01(\tR\fdefinitionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x1e\n" +
	"\x1cListResourceTemplatesRequest\"d\n" +
	"\x1dListResourceTemplatesResponse\x12C\n" +
	"\x05items\x18\x01 \x03(\v2-.resourceplatform.admin.AdminResourceTemplateR\x05items\"$\n" +
	"\"ListResourceTemplateCatalogRequest\"j\n" +
	"#ListResourceTemplateCatalogResponse\x12C\n" +
	"\x05items\x18\x01 \x03(\v2-.resourceplatform.admin.AdminResourceTemplateR\x05items\"=\n" +
	"\x1aGetResourceTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\"\xf6\x01\n" +
	"\x1dCreateResourceTemplateRequest\x124\n" +
	"\x16resource_definition_id\x18\x01 \x01(\tR\x14resourceDefinitionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"stream_key\x18\x04 \x01(\tR\tstreamKey\x12%\n" +
	"\x0econsumer_group\x18\x05 \x01(\tR\rconsumerGroup\x12#\n" +
	"\rtemplate_body\x18\x06 \x01(\tR\ftemplateBody\"\x9d\x03\n" +
	"\x1dUpdateResourceTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\x129\n" +
	"\x16resource_definition_id\x18\x02 \x01(\tH\x00R\x14resourceDefinitionId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01\x12\"\n" +
	"\n" +
	"stream_key\x18\x05 \x01(\tH\x03R\tstreamKey\x88\x01\x01\x12*\n" +
	"\x0econsumer_group\x18\x06 \x01(\tH\x04R\rconsumerGroup\x88\x01\x01\x12(\n" +
	"\rtemplate_body\x18\a \x01(\tH\x05R\ftemplateBody\x88\x01\x01B\x19\n" +
	"\x17_resource_definition_idB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\r\n" +
	"\v_stream_keyB\x11\n" +
	"\x0f_consumer_groupB\x10\n" +
	"\x0e_template_body\"@\n" +
	"\x1dDeleteResourceTemplateRequest\x12\x1f\n" +
	"\vtemplate_id\x18\x01 \x01(\tR\n" +
	"templateId\" \n" +
	"\x1eDeleteResourceTemplateResponse\"<\n" +
	"\x1bGetClusterNodesAdminRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"a\n" +
	"\x1cGetClusterNodesAdminResponse\x12A\n" +
	"\x05items\x18\x01 \x03(\v2+.resourceplatform.admin.AdminK8sClusterNodeR\x05items2\x99\x14\n" +
	"\x13AdminCatalogService\x12r\n" +
	"\x0fListK8sClusters\x12..resourceplatform.admin.ListK8sClustersRequest\x1a/.resourceplatform.admin.ListK8sClustersResponse\x12l\n" +
	"\rGetK8sCluster\x12,.resourceplatform.admin.GetK8sClusterRequest\x1a-.resourceplatform.admin.AdminK8sClusterDetail\x12r\n" +
	"\x10CreateK8sCluster\x12/.resourceplatform.admin.CreateK8sClusterRequest\x1a-.resourceplatform.admin.AdminK8sClusterDetail\x12r\n" +
	"\x10UpdateK8sCluster\x12/.resourceplatform.admin.UpdateK8sClusterRequest\x1a-.resourceplatform.admin.AdminK8sClusterDetail\x12u\n" +
	"\x10DeleteK8sCluster\x12/.resourceplatform.admin.DeleteK8sClusterRequest\x1a0.resourceplatform.admin.DeleteK8sClusterResponse\x12z\n" +
	"\x14RevalidateK8sCluster\x123.resourceplatform.admin.RevalidateK8sClusterRequest\x1a-.resourceplatform.admin.AdminK8sClusterDetail\x12\x8a\x01\n" +
	"\x17ListResourceDefinitions\x126.resourceplatform.admin.ListResourceDefinitionsRequest\x1a7.resourceplatform.admin.ListResourceDefinitionsResponse\x12\x8d\x01\n" +
	"\x18CreateResourceDefinition\x127.resourceplatform.admin.CreateResourceDefinitionRequest\x1a8.resourceplatform.admin.CreateResourceDefinitionResponse\x12\xa8\x01\n" +
	"!ListResourceDefinitionZoneSupport\x12@.resourceplatform.admin.ListResourceDefinitionZoneSupportRequest\x1aA.resourceplatform.admin.ListResourceDefinitionZoneSupportResponse\x12\xb1\x01\n" +
	"$ReplaceResourceDefinitionZoneSupport\x12C.resourceplatform.admin.ReplaceResourceDefinitionZoneSupportRequest\x1aD.resourceplatform.admin.ReplaceResourceDefinitionZoneSupportResponse\x12\x90\x01\n" +
	"\x1eUpdateResourceDefinitionStatus\x12=.resourceplatform.admin.UpdateResourceDefinitionStatusRequest\x1a/.resourceplatform.admin.AdminResourceDefinition\x12\x8d\x01\n" +
	"\x18DeleteResourceDefinition\x127.resourceplatform.admin.DeleteResourceDefinitionRequest\x1a8.resourceplatform.admin.DeleteResourceDefinitionResponse\x12\x96\x01\n" +
	"\x1bListResourceTemplateCatalog\x12:.resourceplatform.admin.ListResourceTemplateCatalogRequest\x1a;.resourceplatform.admin.ListResourceTemplateCatalogResponse\x12\x84\x01\n" +
	"\x15ListResourceTemplates\x124.resourceplatform.admin.ListResourceTemplatesRequest\x1a5.resourceplatform.admin.ListResourceTemplatesResponse\x12x\n" +
	"\x13GetResourceTemplate\x122.resourceplatform.admin.GetResourceTemplateRequest\x1a-.resourceplatform.admin.AdminResourceTemplate\x12~\n" +
	"\x16CreateResourceTemplate\x125.resourceplatform.admin.CreateResourceTemplateRequest\x1a-.resourceplatform.admin.AdminResourceTemplate\x12~\n" +
	"\x16UpdateResourceTemplate\x125.resourceplatform.admin.UpdateResourceTemplateRequest\x1a-.resourceplatform.admin.AdminResourceTemplate\x12\x87\x01\n" +
	"\x16DeleteResourceTemplate\x125.resourceplatform.admin.DeleteResourceTemplateRequest\x1a6.resourceplatform.admin.DeleteResourceTemplateResponse\x12\x81\x01\n" +
	"\x14GetClusterNodesAdmin\x123.resourceplatform.admin.GetClusterNodesAdminRequest\x1a4.resourceplatform.admin.GetClusterNodesAdminResponseB.Z,aurora/pkg/controlplanegrpc;controlplanegrpcb\x06proto3"

var (
	file_resourceplatform_admin_proto_rawDescOnce sync.Once
	file_resourceplatform_admin_proto_rawDescData []byte
)

func file_resourceplatform_admin_proto_rawDescGZIP() []byte {
	file_resourceplatform_admin_proto_rawDescOnce.Do(func() {
		file_resourceplatform_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resourceplatform_admin_proto_rawDesc), len(file_resourceplatform_admin_proto_rawDesc)))
	})
	return file_resourceplatform_admin_proto_rawDescData
}

var file_resourceplatform_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_resourceplatform_admin_proto_goTypes = []any{
	(*AdminK8SClusterListItem)(nil),                      // 0: resourceplatform.admin.AdminK8sClusterListItem
	(*AdminK8SClusterDetail)(nil),                        // 1: resourceplatform.admin.AdminK8sClusterDetail
	(*AdminResourceDefinition)(nil),                      // 2: resourceplatform.admin.AdminResourceDefinition
	(*AdminResourceTemplate)(nil),                        // 3: resourceplatform.admin.AdminResourceTemplate
	(*AdminK8SClusterNode)(nil),                          // 4: resourceplatform.admin.AdminK8sClusterNode
	(*ListK8SClustersRequest)(nil),                       // 5: resourceplatform.admin.ListK8sClustersRequest
	(*ListK8SClustersResponse)(nil),                      // 6: resourceplatform.admin.ListK8sClustersResponse
	(*GetK8SClusterRequest)(nil),                         // 7: resourceplatform.admin.GetK8sClusterRequest
	(*CreateK8SClusterRequest)(nil),                      // 8: resourceplatform.admin.CreateK8sClusterRequest
	(*UpdateK8SClusterRequest)(nil),                      // 9: resourceplatform.admin.UpdateK8sClusterRequest
	(*DeleteK8SClusterRequest)(nil),                      // 10: resourceplatform.admin.DeleteK8sClusterRequest
	(*DeleteK8SClusterResponse)(nil),                     // 11: resourceplatform.admin.DeleteK8sClusterResponse
	(*RevalidateK8SClusterRequest)(nil),                  // 12: resourceplatform.admin.RevalidateK8sClusterRequest
	(*ListResourceDefinitionsRequest)(nil),               // 13: resourceplatform.admin.ListResourceDefinitionsRequest
	(*ListResourceDefinitionsResponse)(nil),              // 14: resourceplatform.admin.ListResourceDefinitionsResponse
	(*CreateResourceDefinitionRequest)(nil),              // 15: resourceplatform.admin.CreateResourceDefinitionRequest
	(*CreateResourceDefinitionResponse)(nil),             // 16: resourceplatform.admin.CreateResourceDefinitionResponse
	(*AdminResourceDefinitionZoneSupport)(nil),           // 17: resourceplatform.admin.AdminResourceDefinitionZoneSupport
	(*ListResourceDefinitionZoneSupportRequest)(nil),     // 18: resourceplatform.admin.ListResourceDefinitionZoneSupportRequest
	(*ListResourceDefinitionZoneSupportResponse)(nil),    // 19: resourceplatform.admin.ListResourceDefinitionZoneSupportResponse
	(*ReplaceResourceDefinitionZoneSupportRequest)(nil),  // 20: resourceplatform.admin.ReplaceResourceDefinitionZoneSupportRequest
	(*ReplaceResourceDefinitionZoneSupportResponse)(nil), // 21: resourceplatform.admin.ReplaceResourceDefinitionZoneSupportResponse
	(*DeleteResourceDefinitionRequest)(nil),              // 22: resourceplatform.admin.DeleteResourceDefinitionRequest
	(*DeleteResourceDefinitionResponse)(nil),             // 23: resourceplatform.admin.DeleteResourceDefinitionResponse
	(*UpdateResourceDefinitionStatusRequest)(nil),        // 24: resourceplatform.admin.UpdateResourceDefinitionStatusRequest
	(*ListResourceTemplatesRequest)(nil),                 // 25: resourceplatform.admin.ListResourceTemplatesRequest
	(*ListResourceTemplatesResponse)(nil),                // 26: resourceplatform.admin.ListResourceTemplatesResponse
	(*ListResourceTemplateCatalogRequest)(nil),           // 27: resourceplatform.admin.ListResourceTemplateCatalogRequest
	(*ListResourceTemplateCatalogResponse)(nil),          // 28: resourceplatform.admin.ListResourceTemplateCatalogResponse
	(*GetResourceTemplateRequest)(nil),                   // 29: resourceplatform.admin.GetResourceTemplateRequest
	(*CreateResourceTemplateRequest)(nil),                // 30: resourceplatform.admin.CreateResourceTemplateRequest
	(*UpdateResourceTemplateRequest)(nil),                // 31: resourceplatform.admin.UpdateResourceTemplateRequest
	(*DeleteResourceTemplateRequest)(nil),                // 32: resourceplatform.admin.DeleteResourceTemplateRequest
	(*DeleteResourceTemplateResponse)(nil),               // 33: resourceplatform.admin.DeleteResourceTemplateResponse
	(*GetClusterNodesAdminRequest)(nil),                  // 34: resourceplatform.admin.GetClusterNodesAdminRequest
	(*GetClusterNodesAdminResponse)(nil),                 // 35: resourceplatform.admin.GetClusterNodesAdminResponse
}
var file_resourceplatform_admin_proto_depIdxs = []int32{
	0,  // 0: resourceplatform.admin.ListK8sClustersResponse.items:type_name -> resourceplatform.admin.AdminK8sClusterListItem
	2,  // 1: resourceplatform.admin.ListResourceDefinitionsResponse.items:type_name -> resourceplatform.admin.AdminResourceDefinition
	17, // 2: resourceplatform.admin.ListResourceDefinitionZoneSupportResponse.items:type_name -> resourceplatform.admin.AdminResourceDefinitionZoneSupport
	3,  // 3: resourceplatform.admin.ListResourceTemplatesResponse.items:type_name -> resourceplatform.admin.AdminResourceTemplate
	3,  // 4: resourceplatform.admin.ListResourceTemplateCatalogResponse.items:type_name -> resourceplatform.admin.AdminResourceTemplate
	4,  // 5: resourceplatform.admin.GetClusterNodesAdminResponse.items:type_name -> resourceplatform.admin.AdminK8sClusterNode
	5,  // 6: resourceplatform.admin.AdminCatalogService.ListK8sClusters:input_type -> resourceplatform.admin.ListK8sClustersRequest
	7,  // 7: resourceplatform.admin.AdminCatalogService.GetK8sCluster:input_type -> resourceplatform.admin.GetK8sClusterRequest
	8,  // 8: resourceplatform.admin.AdminCatalogService.CreateK8sCluster:input_type -> resourceplatform.admin.CreateK8sClusterRequest
	9,  // 9: resourceplatform.admin.AdminCatalogService.UpdateK8sCluster:input_type -> resourceplatform.admin.UpdateK8sClusterRequest
	10, // 10: resourceplatform.admin.AdminCatalogService.DeleteK8sCluster:input_type -> resourceplatform.admin.DeleteK8sClusterRequest
	12, // 11: resourceplatform.admin.AdminCatalogService.RevalidateK8sCluster:input_type -> resourceplatform.admin.RevalidateK8sClusterRequest
	13, // 12: resourceplatform.admin.AdminCatalogService.ListResourceDefinitions:input_type -> resourceplatform.admin.ListResourceDefinitionsRequest
	15, // 13: resourceplatform.admin.AdminCatalogService.CreateResourceDefinition:input_type -> resourceplatform.admin.CreateResourceDefinitionRequest
	18, // 14: resourceplatform.admin.AdminCatalogService.ListResourceDefinitionZoneSupport:input_type -> resourceplatform.admin.ListResourceDefinitionZoneSupportRequest
	20, // 15: resourceplatform.admin.AdminCatalogService.ReplaceResourceDefinitionZoneSupport:input_type -> resourceplatform.admin.ReplaceResourceDefinitionZoneSupportRequest
	24, // 16: resourceplatform.admin.AdminCatalogService.UpdateResourceDefinitionStatus:input_type -> resourceplatform.admin.UpdateResourceDefinitionStatusRequest
	22, // 17: resourceplatform.admin.AdminCatalogService.DeleteResourceDefinition:input_type -> resourceplatform.admin.DeleteResourceDefinitionRequest
	27, // 18: resourceplatform.admin.AdminCatalogService.ListResourceTemplateCatalog:input_type -> resourceplatform.admin.ListResourceTemplateCatalogRequest
	25, // 19: resourceplatform.admin.AdminCatalogService.ListResourceTemplates:input_type -> resourceplatform.admin.ListResourceTemplatesRequest
	29, // 20: resourceplatform.admin.AdminCatalogService.GetResourceTemplate:input_type -> resourceplatform.admin.GetResourceTemplateRequest
	30, // 21: resourceplatform.admin.AdminCatalogService.CreateResourceTemplate:input_type -> resourceplatform.admin.CreateResourceTemplateRequest
	31, // 22: resourceplatform.admin.AdminCatalogService.UpdateResourceTemplate:input_type -> resourceplatform.admin.UpdateResourceTemplateRequest
	32, // 23: resourceplatform.admin.AdminCatalogService.DeleteResourceTemplate:input_type -> resourceplatform.admin.DeleteResourceTemplateRequest
	34, // 24: resourceplatform.admin.AdminCatalogService.GetClusterNodesAdmin:input_type -> resourceplatform.admin.GetClusterNodesAdminRequest
	6,  // 25: resourceplatform.admin.AdminCatalogService.ListK8sClusters:output_type -> resourceplatform.admin.ListK8sClustersResponse
	1,  // 26: resourceplatform.admin.AdminCatalogService.GetK8sCluster:output_type -> resourceplatform.admin.AdminK8sClusterDetail
	1,  // 27: resourceplatform.admin.AdminCatalogService.CreateK8sCluster:output_type -> resourceplatform.admin.AdminK8sClusterDetail
	1,  // 28: resourceplatform.admin.AdminCatalogService.UpdateK8sCluster:output_type -> resourceplatform.admin.AdminK8sClusterDetail
	11, // 29: resourceplatform.admin.AdminCatalogService.DeleteK8sCluster:output_type -> resourceplatform.admin.DeleteK8sClusterResponse
	1,  // 30: resourceplatform.admin.AdminCatalogService.RevalidateK8sCluster:output_type -> resourceplatform.admin.AdminK8sClusterDetail
	14, // 31: resourceplatform.admin.AdminCatalogService.ListResourceDefinitions:output_type -> resourceplatform.admin.ListResourceDefinitionsResponse
	16, // 32: resourceplatform.admin.AdminCatalogService.CreateResourceDefinition:output_type -> resourceplatform.admin.CreateResourceDefinitionResponse
	19, // 33: resourceplatform.admin.AdminCatalogService.ListResourceDefinitionZoneSupport:output_type -> resourceplatform.admin.ListResourceDefinitionZoneSupportResponse
	21, // 34: resourceplatform.admin.AdminCatalogService.ReplaceResourceDefinitionZoneSupport:output_type -> resourceplatform.admin.ReplaceResourceDefinitionZoneSupportResponse
	2,  // 35: resourceplatform.admin.AdminCatalogService.UpdateResourceDefinitionStatus:output_type -> resourceplatform.admin.AdminResourceDefinition
	23, // 36: resourceplatform.admin.AdminCatalogService.DeleteResourceDefinition:output_type -> resourceplatform.admin.DeleteResourceDefinitionResponse
	28, // 37: resourceplatform.admin.AdminCatalogService.ListResourceTemplateCatalog:output_type -> resourceplatform.admin.ListResourceTemplateCatalogResponse
	26, // 38: resourceplatform.admin.AdminCatalogService.ListResourceTemplates:output_type -> resourceplatform.admin.ListResourceTemplatesResponse
	3,  // 39: resourceplatform.admin.AdminCatalogService.GetResourceTemplate:output_type -> resourceplatform.admin.AdminResourceTemplate
	3,  // 40: resourceplatform.admin.AdminCatalogService.CreateResourceTemplate:output_type -> resourceplatform.admin.AdminResourceTemplate
	3,  // 41: resourceplatform.admin.AdminCatalogService.UpdateResourceTemplate:output_type -> resourceplatform.admin.AdminResourceTemplate
	33, // 42: resourceplatform.admin.AdminCatalogService.DeleteResourceTemplate:output_type -> resourceplatform.admin.DeleteResourceTemplateResponse
	35, // 43: resourceplatform.admin.AdminCatalogService.GetClusterNodesAdmin:output_type -> resourceplatform.admin.GetClusterNodesAdminResponse
	25, // [25:44] is the sub-list for method output_type
	6,  // [6:25] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_resourceplatform_admin_proto_init() }
func file_resourceplatform_admin_proto_init() {
	if File_resourceplatform_admin_proto != nil {
		return
	}
	file_resourceplatform_admin_proto_msgTypes[31].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resourceplatform_admin_proto_rawDesc), len(file_resourceplatform_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resourceplatform_admin_proto_goTypes,
		DependencyIndexes: file_resourceplatform_admin_proto_depIdxs,
		MessageInfos:      file_resourceplatform_admin_proto_msgTypes,
	}.Build()
	File_resourceplatform_admin_proto = out.File
	file_resourceplatform_admin_proto_goTypes = nil
	file_resourceplatform_admin_proto_depIdxs = nil
}
