/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedZonesIndexRouteImport } from './routes/_authenticated/zones/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedResourceTypesIndexRouteImport } from './routes/_authenticated/resource-types/index'
import { Route as AuthenticatedResourceTemplatesIndexRouteImport } from './routes/_authenticated/resource-templates/index'
import { Route as AuthenticatedResourceDefinitionIndexRouteImport } from './routes/_authenticated/resource-definition/index'
import { Route as AuthenticatedPlansIndexRouteImport } from './routes/_authenticated/plans/index'
import { Route as AuthenticatedMarketplaceIndexRouteImport } from './routes/_authenticated/marketplace/index'
import { Route as AuthenticatedK8sIndexRouteImport } from './routes/_authenticated/k8s/index'
import { Route as AuthenticatedHypervisorIndexRouteImport } from './routes/_authenticated/hypervisor/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedZonesNewRouteImport } from './routes/_authenticated/zones/new'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedRolesNewRouteImport } from './routes/_authenticated/roles/new'
import { Route as AuthenticatedResourceTemplatesNewRouteImport } from './routes/_authenticated/resource-templates/new'
import { Route as AuthenticatedResourceTemplatesTemplateIdRouteImport } from './routes/_authenticated/resource-templates/$templateId'
import { Route as AuthenticatedPlansNewRouteImport } from './routes/_authenticated/plans/new'
import { Route as AuthenticatedMarketplaceNewRouteImport } from './routes/_authenticated/marketplace/new'
import { Route as AuthenticatedMarketplaceAppIdRouteImport } from './routes/_authenticated/marketplace/$appId'
import { Route as AuthenticatedK8sNewRouteImport } from './routes/_authenticated/k8s/new'
import { Route as AuthenticatedK8sClusterIdRouteImport } from './routes/_authenticated/k8s/$clusterId'
import { Route as AuthenticatedHypervisorNodeIdRouteImport } from './routes/_authenticated/hypervisor/$nodeId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedResourceTemplatesTemplateIdEditRouteImport } from './routes/_authenticated/resource-templates/$templateId.edit'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedZonesIndexRoute = AuthenticatedZonesIndexRouteImport.update({
  id: '/zones/',
  path: '/zones/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourceTypesIndexRoute =
  AuthenticatedResourceTypesIndexRouteImport.update({
    id: '/resource-types/',
    path: '/resource-types/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResourceTemplatesIndexRoute =
  AuthenticatedResourceTemplatesIndexRouteImport.update({
    id: '/resource-templates/',
    path: '/resource-templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResourceDefinitionIndexRoute =
  AuthenticatedResourceDefinitionIndexRouteImport.update({
    id: '/resource-definition/',
    path: '/resource-definition/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansIndexRoute = AuthenticatedPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceIndexRoute =
  AuthenticatedMarketplaceIndexRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedK8sIndexRoute = AuthenticatedK8sIndexRouteImport.update({
  id: '/k8s/',
  path: '/k8s/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHypervisorIndexRoute =
  AuthenticatedHypervisorIndexRouteImport.update({
    id: '/hypervisor/',
    path: '/hypervisor/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedZonesNewRoute = AuthenticatedZonesNewRouteImport.update({
  id: '/zones/new',
  path: '/zones/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedRolesNewRoute = AuthenticatedRolesNewRouteImport.update({
  id: '/roles/new',
  path: '/roles/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResourceTemplatesNewRoute =
  AuthenticatedResourceTemplatesNewRouteImport.update({
    id: '/resource-templates/new',
    path: '/resource-templates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResourceTemplatesTemplateIdRoute =
  AuthenticatedResourceTemplatesTemplateIdRouteImport.update({
    id: '/resource-templates/$templateId',
    path: '/resource-templates/$templateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansNewRoute = AuthenticatedPlansNewRouteImport.update({
  id: '/plans/new',
  path: '/plans/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceNewRoute =
  AuthenticatedMarketplaceNewRouteImport.update({
    id: '/marketplace/new',
    path: '/marketplace/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketplaceAppIdRoute =
  AuthenticatedMarketplaceAppIdRouteImport.update({
    id: '/marketplace/$appId',
    path: '/marketplace/$appId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedK8sNewRoute = AuthenticatedK8sNewRouteImport.update({
  id: '/k8s/new',
  path: '/k8s/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedK8sClusterIdRoute =
  AuthenticatedK8sClusterIdRouteImport.update({
    id: '/k8s/$clusterId',
    path: '/k8s/$clusterId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHypervisorNodeIdRoute =
  AuthenticatedHypervisorNodeIdRouteImport.update({
    id: '/hypervisor/$nodeId',
    path: '/hypervisor/$nodeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResourceTemplatesTemplateIdEditRoute =
  AuthenticatedResourceTemplatesTemplateIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedResourceTemplatesTemplateIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/hypervisor/$nodeId': typeof AuthenticatedHypervisorNodeIdRoute
  '/k8s/$clusterId': typeof AuthenticatedK8sClusterIdRoute
  '/k8s/new': typeof AuthenticatedK8sNewRoute
  '/marketplace/$appId': typeof AuthenticatedMarketplaceAppIdRoute
  '/marketplace/new': typeof AuthenticatedMarketplaceNewRoute
  '/plans/new': typeof AuthenticatedPlansNewRoute
  '/resource-templates/$templateId': typeof AuthenticatedResourceTemplatesTemplateIdRouteWithChildren
  '/resource-templates/new': typeof AuthenticatedResourceTemplatesNewRoute
  '/roles/new': typeof AuthenticatedRolesNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/zones/new': typeof AuthenticatedZonesNewRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/hypervisor/': typeof AuthenticatedHypervisorIndexRoute
  '/k8s/': typeof AuthenticatedK8sIndexRoute
  '/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/plans/': typeof AuthenticatedPlansIndexRoute
  '/resource-definition/': typeof AuthenticatedResourceDefinitionIndexRoute
  '/resource-templates/': typeof AuthenticatedResourceTemplatesIndexRoute
  '/resource-types/': typeof AuthenticatedResourceTypesIndexRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/zones/': typeof AuthenticatedZonesIndexRoute
  '/resource-templates/$templateId/edit': typeof AuthenticatedResourceTemplatesTemplateIdEditRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/hypervisor/$nodeId': typeof AuthenticatedHypervisorNodeIdRoute
  '/k8s/$clusterId': typeof AuthenticatedK8sClusterIdRoute
  '/k8s/new': typeof AuthenticatedK8sNewRoute
  '/marketplace/$appId': typeof AuthenticatedMarketplaceAppIdRoute
  '/marketplace/new': typeof AuthenticatedMarketplaceNewRoute
  '/plans/new': typeof AuthenticatedPlansNewRoute
  '/resource-templates/$templateId': typeof AuthenticatedResourceTemplatesTemplateIdRouteWithChildren
  '/resource-templates/new': typeof AuthenticatedResourceTemplatesNewRoute
  '/roles/new': typeof AuthenticatedRolesNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/zones/new': typeof AuthenticatedZonesNewRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/hypervisor': typeof AuthenticatedHypervisorIndexRoute
  '/k8s': typeof AuthenticatedK8sIndexRoute
  '/marketplace': typeof AuthenticatedMarketplaceIndexRoute
  '/plans': typeof AuthenticatedPlansIndexRoute
  '/resource-definition': typeof AuthenticatedResourceDefinitionIndexRoute
  '/resource-templates': typeof AuthenticatedResourceTemplatesIndexRoute
  '/resource-types': typeof AuthenticatedResourceTypesIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/zones': typeof AuthenticatedZonesIndexRoute
  '/resource-templates/$templateId/edit': typeof AuthenticatedResourceTemplatesTemplateIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/hypervisor/$nodeId': typeof AuthenticatedHypervisorNodeIdRoute
  '/_authenticated/k8s/$clusterId': typeof AuthenticatedK8sClusterIdRoute
  '/_authenticated/k8s/new': typeof AuthenticatedK8sNewRoute
  '/_authenticated/marketplace/$appId': typeof AuthenticatedMarketplaceAppIdRoute
  '/_authenticated/marketplace/new': typeof AuthenticatedMarketplaceNewRoute
  '/_authenticated/plans/new': typeof AuthenticatedPlansNewRoute
  '/_authenticated/resource-templates/$templateId': typeof AuthenticatedResourceTemplatesTemplateIdRouteWithChildren
  '/_authenticated/resource-templates/new': typeof AuthenticatedResourceTemplatesNewRoute
  '/_authenticated/roles/new': typeof AuthenticatedRolesNewRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/zones/new': typeof AuthenticatedZonesNewRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/hypervisor/': typeof AuthenticatedHypervisorIndexRoute
  '/_authenticated/k8s/': typeof AuthenticatedK8sIndexRoute
  '/_authenticated/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/_authenticated/plans/': typeof AuthenticatedPlansIndexRoute
  '/_authenticated/resource-definition/': typeof AuthenticatedResourceDefinitionIndexRoute
  '/_authenticated/resource-templates/': typeof AuthenticatedResourceTemplatesIndexRoute
  '/_authenticated/resource-types/': typeof AuthenticatedResourceTypesIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/zones/': typeof AuthenticatedZonesIndexRoute
  '/_authenticated/resource-templates/$templateId/edit': typeof AuthenticatedResourceTemplatesTemplateIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/errors/$error'
    | '/hypervisor/$nodeId'
    | '/k8s/$clusterId'
    | '/k8s/new'
    | '/marketplace/$appId'
    | '/marketplace/new'
    | '/plans/new'
    | '/resource-templates/$templateId'
    | '/resource-templates/new'
    | '/roles/new'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/zones/new'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps/'
    | '/chats/'
    | '/help-center/'
    | '/hypervisor/'
    | '/k8s/'
    | '/marketplace/'
    | '/plans/'
    | '/resource-definition/'
    | '/resource-templates/'
    | '/resource-types/'
    | '/roles/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/zones/'
    | '/resource-templates/$templateId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/hypervisor/$nodeId'
    | '/k8s/$clusterId'
    | '/k8s/new'
    | '/marketplace/$appId'
    | '/marketplace/new'
    | '/plans/new'
    | '/resource-templates/$templateId'
    | '/resource-templates/new'
    | '/roles/new'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/zones/new'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/hypervisor'
    | '/k8s'
    | '/marketplace'
    | '/plans'
    | '/resource-definition'
    | '/resource-templates'
    | '/resource-types'
    | '/roles'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/zones'
    | '/resource-templates/$templateId/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/errors/$error'
    | '/_authenticated/hypervisor/$nodeId'
    | '/_authenticated/k8s/$clusterId'
    | '/_authenticated/k8s/new'
    | '/_authenticated/marketplace/$appId'
    | '/_authenticated/marketplace/new'
    | '/_authenticated/plans/new'
    | '/_authenticated/resource-templates/$templateId'
    | '/_authenticated/resource-templates/new'
    | '/_authenticated/roles/new'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/zones/new'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/hypervisor/'
    | '/_authenticated/k8s/'
    | '/_authenticated/marketplace/'
    | '/_authenticated/plans/'
    | '/_authenticated/resource-definition/'
    | '/_authenticated/resource-templates/'
    | '/_authenticated/resource-types/'
    | '/_authenticated/roles/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/zones/'
    | '/_authenticated/resource-templates/$templateId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/zones/': {
      id: '/_authenticated/zones/'
      path: '/zones'
      fullPath: '/zones/'
      preLoaderRoute: typeof AuthenticatedZonesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resource-types/': {
      id: '/_authenticated/resource-types/'
      path: '/resource-types'
      fullPath: '/resource-types/'
      preLoaderRoute: typeof AuthenticatedResourceTypesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resource-templates/': {
      id: '/_authenticated/resource-templates/'
      path: '/resource-templates'
      fullPath: '/resource-templates/'
      preLoaderRoute: typeof AuthenticatedResourceTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resource-definition/': {
      id: '/_authenticated/resource-definition/'
      path: '/resource-definition'
      fullPath: '/resource-definition/'
      preLoaderRoute: typeof AuthenticatedResourceDefinitionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/': {
      id: '/_authenticated/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AuthenticatedPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/': {
      id: '/_authenticated/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AuthenticatedMarketplaceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/k8s/': {
      id: '/_authenticated/k8s/'
      path: '/k8s'
      fullPath: '/k8s/'
      preLoaderRoute: typeof AuthenticatedK8sIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hypervisor/': {
      id: '/_authenticated/hypervisor/'
      path: '/hypervisor'
      fullPath: '/hypervisor/'
      preLoaderRoute: typeof AuthenticatedHypervisorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/zones/new': {
      id: '/_authenticated/zones/new'
      path: '/zones/new'
      fullPath: '/zones/new'
      preLoaderRoute: typeof AuthenticatedZonesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/roles/new': {
      id: '/_authenticated/roles/new'
      path: '/roles/new'
      fullPath: '/roles/new'
      preLoaderRoute: typeof AuthenticatedRolesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resource-templates/new': {
      id: '/_authenticated/resource-templates/new'
      path: '/resource-templates/new'
      fullPath: '/resource-templates/new'
      preLoaderRoute: typeof AuthenticatedResourceTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resource-templates/$templateId': {
      id: '/_authenticated/resource-templates/$templateId'
      path: '/resource-templates/$templateId'
      fullPath: '/resource-templates/$templateId'
      preLoaderRoute: typeof AuthenticatedResourceTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plans/new': {
      id: '/_authenticated/plans/new'
      path: '/plans/new'
      fullPath: '/plans/new'
      preLoaderRoute: typeof AuthenticatedPlansNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/new': {
      id: '/_authenticated/marketplace/new'
      path: '/marketplace/new'
      fullPath: '/marketplace/new'
      preLoaderRoute: typeof AuthenticatedMarketplaceNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace/$appId': {
      id: '/_authenticated/marketplace/$appId'
      path: '/marketplace/$appId'
      fullPath: '/marketplace/$appId'
      preLoaderRoute: typeof AuthenticatedMarketplaceAppIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/k8s/new': {
      id: '/_authenticated/k8s/new'
      path: '/k8s/new'
      fullPath: '/k8s/new'
      preLoaderRoute: typeof AuthenticatedK8sNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/k8s/$clusterId': {
      id: '/_authenticated/k8s/$clusterId'
      path: '/k8s/$clusterId'
      fullPath: '/k8s/$clusterId'
      preLoaderRoute: typeof AuthenticatedK8sClusterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hypervisor/$nodeId': {
      id: '/_authenticated/hypervisor/$nodeId'
      path: '/hypervisor/$nodeId'
      fullPath: '/hypervisor/$nodeId'
      preLoaderRoute: typeof AuthenticatedHypervisorNodeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resource-templates/$templateId/edit': {
      id: '/_authenticated/resource-templates/$templateId/edit'
      path: '/edit'
      fullPath: '/resource-templates/$templateId/edit'
      preLoaderRoute: typeof AuthenticatedResourceTemplatesTemplateIdEditRouteImport
      parentRoute: typeof AuthenticatedResourceTemplatesTemplateIdRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedResourceTemplatesTemplateIdRouteChildren {
  AuthenticatedResourceTemplatesTemplateIdEditRoute: typeof AuthenticatedResourceTemplatesTemplateIdEditRoute
}

const AuthenticatedResourceTemplatesTemplateIdRouteChildren: AuthenticatedResourceTemplatesTemplateIdRouteChildren =
  {
    AuthenticatedResourceTemplatesTemplateIdEditRoute:
      AuthenticatedResourceTemplatesTemplateIdEditRoute,
  }

const AuthenticatedResourceTemplatesTemplateIdRouteWithChildren =
  AuthenticatedResourceTemplatesTemplateIdRoute._addFileChildren(
    AuthenticatedResourceTemplatesTemplateIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHypervisorNodeIdRoute: typeof AuthenticatedHypervisorNodeIdRoute
  AuthenticatedK8sClusterIdRoute: typeof AuthenticatedK8sClusterIdRoute
  AuthenticatedK8sNewRoute: typeof AuthenticatedK8sNewRoute
  AuthenticatedMarketplaceAppIdRoute: typeof AuthenticatedMarketplaceAppIdRoute
  AuthenticatedMarketplaceNewRoute: typeof AuthenticatedMarketplaceNewRoute
  AuthenticatedPlansNewRoute: typeof AuthenticatedPlansNewRoute
  AuthenticatedResourceTemplatesTemplateIdRoute: typeof AuthenticatedResourceTemplatesTemplateIdRouteWithChildren
  AuthenticatedResourceTemplatesNewRoute: typeof AuthenticatedResourceTemplatesNewRoute
  AuthenticatedRolesNewRoute: typeof AuthenticatedRolesNewRoute
  AuthenticatedZonesNewRoute: typeof AuthenticatedZonesNewRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedHypervisorIndexRoute: typeof AuthenticatedHypervisorIndexRoute
  AuthenticatedK8sIndexRoute: typeof AuthenticatedK8sIndexRoute
  AuthenticatedMarketplaceIndexRoute: typeof AuthenticatedMarketplaceIndexRoute
  AuthenticatedPlansIndexRoute: typeof AuthenticatedPlansIndexRoute
  AuthenticatedResourceDefinitionIndexRoute: typeof AuthenticatedResourceDefinitionIndexRoute
  AuthenticatedResourceTemplatesIndexRoute: typeof AuthenticatedResourceTemplatesIndexRoute
  AuthenticatedResourceTypesIndexRoute: typeof AuthenticatedResourceTypesIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedZonesIndexRoute: typeof AuthenticatedZonesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHypervisorNodeIdRoute: AuthenticatedHypervisorNodeIdRoute,
  AuthenticatedK8sClusterIdRoute: AuthenticatedK8sClusterIdRoute,
  AuthenticatedK8sNewRoute: AuthenticatedK8sNewRoute,
  AuthenticatedMarketplaceAppIdRoute: AuthenticatedMarketplaceAppIdRoute,
  AuthenticatedMarketplaceNewRoute: AuthenticatedMarketplaceNewRoute,
  AuthenticatedPlansNewRoute: AuthenticatedPlansNewRoute,
  AuthenticatedResourceTemplatesTemplateIdRoute:
    AuthenticatedResourceTemplatesTemplateIdRouteWithChildren,
  AuthenticatedResourceTemplatesNewRoute:
    AuthenticatedResourceTemplatesNewRoute,
  AuthenticatedRolesNewRoute: AuthenticatedRolesNewRoute,
  AuthenticatedZonesNewRoute: AuthenticatedZonesNewRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedHypervisorIndexRoute: AuthenticatedHypervisorIndexRoute,
  AuthenticatedK8sIndexRoute: AuthenticatedK8sIndexRoute,
  AuthenticatedMarketplaceIndexRoute: AuthenticatedMarketplaceIndexRoute,
  AuthenticatedPlansIndexRoute: AuthenticatedPlansIndexRoute,
  AuthenticatedResourceDefinitionIndexRoute:
    AuthenticatedResourceDefinitionIndexRoute,
  AuthenticatedResourceTemplatesIndexRoute:
    AuthenticatedResourceTemplatesIndexRoute,
  AuthenticatedResourceTypesIndexRoute: AuthenticatedResourceTypesIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedZonesIndexRoute: AuthenticatedZonesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
